import 'package:dartz/dartz.dart';
import '../../../../core/error/failures.dart';
import '../../../../core/usecases/usecase.dart';
import '../entities/driver_location.dart';
import '../repositories/tracking_repository.dart';

/// Use case for updating driver location (driver app)
class UpdateDriverLocation
    implements UseCase<DriverLocation, UpdateDriverLocationParams> {
  final TrackingRepository repository;

  UpdateDriverLocation(this.repository);

  @override
  Future<Either<Failure, DriverLocation>> call(
    UpdateDriverLocationParams params,
  ) async {
    // Validation
    if (params.driverId.isEmpty) {
      return Left(ValidationFailure('Driver ID cannot be empty'));
    }

    if (params.latitude < -90 || params.latitude > 90) {
      return Left(ValidationFailure('Invalid latitude value'));
    }

    if (params.longitude < -180 || params.longitude > 180) {
      return Left(ValidationFailure('Invalid longitude value'));
    }

    // Create location entity
    final location = DriverLocation(
      id: '', // Will be generated by backend
      driverId: params.driverId,
      shipmentId: params.shipmentId,
      latitude: params.latitude,
      longitude: params.longitude,
      accuracy: params.accuracy,
      altitude: params.altitude,
      speed: params.speed,
      heading: params.heading,
      timestamp: DateTime.now(),
      createdAt: DateTime.now(),
    );

    return await repository.updateDriverLocation(location);
  }
}

/// Parameters for UpdateDriverLocation use case
class UpdateDriverLocationParams {
  final String driverId;
  final String? shipmentId;
  final double latitude;
  final double longitude;
  final double? accuracy;
  final double? altitude;
  final double? speed;
  final double? heading;

  const UpdateDriverLocationParams({
    required this.driverId,
    this.shipmentId,
    required this.latitude,
    required this.longitude,
    this.accuracy,
    this.altitude,
    this.speed,
    this.heading,
  });

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is UpdateDriverLocationParams &&
        other.driverId == driverId &&
        other.shipmentId == shipmentId &&
        other.latitude == latitude &&
        other.longitude == longitude;
  }

  @override
  int get hashCode => Object.hash(driverId, shipmentId, latitude, longitude);
}
