-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.deliveries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid,
  driver_id uuid,
  status character varying DEFAULT 'pending'::character varying,
  pickup_time timestamp with time zone,
  delivery_time timestamp with time zone,
  pickup_signature text,
  delivery_signature text,
  pickup_photo text,
  delivery_photo text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT deliveries_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT deliveries_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.driver_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  shipment_id uuid,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  accuracy numeric,
  altitude numeric,
  speed numeric,
  heading numeric,
  timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_locations_pkey PRIMARY KEY (id),
  CONSTRAINT driver_locations_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id),
  CONSTRAINT driver_locations_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.driver_performance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid,
  month_year character varying NOT NULL,
  total_deliveries integer DEFAULT 0,
  completed_deliveries integer DEFAULT 0,
  cancelled_deliveries integer DEFAULT 0,
  average_rating numeric DEFAULT 0.00,
  total_distance_km numeric DEFAULT 0.00,
  fuel_consumption_liters numeric DEFAULT 0.00,
  on_time_percentage numeric DEFAULT 0.00,
  customer_ratings jsonb,
  performance_score numeric DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_performance_pkey PRIMARY KEY (id),
  CONSTRAINT driver_performance_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying DEFAULT 'info'::character varying,
  related_table character varying,
  related_id uuid,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.order_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  product_id uuid NOT NULL,
  requested_quantity numeric NOT NULL,
  confirmed_quantity numeric DEFAULT 0,
  unit_price numeric NOT NULL,
  subtotal numeric NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_details_pkey PRIMARY KEY (id),
  CONSTRAINT order_details_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_details_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number character varying NOT NULL UNIQUE,
  customer_id uuid NOT NULL,
  order_date timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'shipped'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  total_quantity numeric NOT NULL,
  confirmed_quantity numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  admin_notes text,
  customer_notes text,
  confirmed_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pickup_address text,
  delivery_address text,
  pickup_date timestamp with time zone,
  delivery_date timestamp with time zone,
  notes text,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  price_per_kg numeric NOT NULL,
  unit character varying DEFAULT 'ton'::character varying,
  stock_available numeric DEFAULT 0,
  minimum_order numeric DEFAULT 1,
  category character varying NOT NULL DEFAULT 'Palm Shell'::character varying,
  product_code character varying UNIQUE,
  specifications text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  stock_quantity integer DEFAULT 0,
  min_order_quantity integer DEFAULT 1,
  CONSTRAINT products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  full_name character varying,
  role_id integer,
  phone character varying,
  address text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  role text,
  avatar_url text,
  city character varying,
  province character varying,
  postal_code character varying,
  driver_license character varying,
  vehicle_type character varying,
  vehicle_plate character varying,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.roles (
  id integer NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
  name character varying NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.shipments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  delivery_note_number character varying NOT NULL UNIQUE,
  delivery_note_url text,
  proof_of_delivery_url text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in_transit'::character varying, 'arrived'::character varying, 'completed'::character varying]::text[])),
  assigned_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  estimated_arrival timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  estimated_delivery timestamp with time zone,
  actual_delivery timestamp with time zone,
  tracking_number character varying,
  CONSTRAINT shipments_pkey PRIMARY KEY (id),
  CONSTRAINT shipments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT shipments_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  driver_id uuid,
  title character varying NOT NULL,
  description text,
  status USER-DEFINED DEFAULT 'Scheduled'::task_status,
  priority integer DEFAULT 1,
  scheduled_date timestamp with time zone,
  completed_date timestamp with time zone,
  location_lat numeric,
  location_lng numeric,
  address text,
  notes text,
  attachments jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id),
  CONSTRAINT tasks_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);