// Mocks generated by Mockito 5.4.6 from annotations
// in cangkang_sawit_app/test/features/products/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cangkang_sawit_app/features/products/data/datasources/product_remote_datasource.dart'
    as _i4;
import 'package:cangkang_sawit_app/features/products/data/models/product_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductModel_1 extends _i1.SmartFake implements _i3.ProductModel {
  _FakeProductModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i4.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.SupabaseClient);

  @override
  _i5.Future<List<_i3.ProductModel>> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i5.Future<List<_i3.ProductModel>>.value(
              <_i3.ProductModel>[],
            ),
          )
          as _i5.Future<List<_i3.ProductModel>>);

  @override
  _i5.Future<_i3.ProductModel> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i5.Future<_i3.ProductModel>.value(
              _FakeProductModel_1(
                this,
                Invocation.method(#getProductById, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.ProductModel>);

  @override
  _i5.Future<List<_i3.ProductModel>> searchProducts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [query]),
            returnValue: _i5.Future<List<_i3.ProductModel>>.value(
              <_i3.ProductModel>[],
            ),
          )
          as _i5.Future<List<_i3.ProductModel>>);

  @override
  _i5.Future<_i3.ProductModel> createProduct({
    required String? name,
    String? description,
    required double? pricePerTon,
    double? stockAvailable,
    double? minimumOrder,
    String? category,
    String? specifications,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [], {
              #name: name,
              #description: description,
              #pricePerTon: pricePerTon,
              #stockAvailable: stockAvailable,
              #minimumOrder: minimumOrder,
              #category: category,
              #specifications: specifications,
            }),
            returnValue: _i5.Future<_i3.ProductModel>.value(
              _FakeProductModel_1(
                this,
                Invocation.method(#createProduct, [], {
                  #name: name,
                  #description: description,
                  #pricePerTon: pricePerTon,
                  #stockAvailable: stockAvailable,
                  #minimumOrder: minimumOrder,
                  #category: category,
                  #specifications: specifications,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ProductModel>);

  @override
  _i5.Future<_i3.ProductModel> updateProduct({
    required String? id,
    String? name,
    String? description,
    double? pricePerTon,
    double? stockAvailable,
    double? minimumOrder,
    bool? isActive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [], {
              #id: id,
              #name: name,
              #description: description,
              #pricePerTon: pricePerTon,
              #stockAvailable: stockAvailable,
              #minimumOrder: minimumOrder,
              #isActive: isActive,
            }),
            returnValue: _i5.Future<_i3.ProductModel>.value(
              _FakeProductModel_1(
                this,
                Invocation.method(#updateProduct, [], {
                  #id: id,
                  #name: name,
                  #description: description,
                  #pricePerTon: pricePerTon,
                  #stockAvailable: stockAvailable,
                  #minimumOrder: minimumOrder,
                  #isActive: isActive,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ProductModel>);

  @override
  _i5.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
